[package]

name = "cryptopals"
version = "0.0.1"
authors = ["Vítězslav Čížek <civ@blema.cz>"]

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl"

[dependencies.rust-crypto]
git = "https://github.com/DaGenix/rust-crypto"
